[ADF-4280] fix initial display for search-sorting-picker (#4522)
* [ADF-4280] fix initial display for search-sorting-picker

* [ADF-4280] fix unrelated error TS6133: 'renderingQueueServices' is declared but its value is never read

* [ADF-4280] update e2e test